version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db-container
    hostname: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=Oracle123!
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true
    volumes:
      - oracle_data:/opt/oracle/oradata
      - oracle_backup:/opt/oracle/backup
      - ./scripts:/opt/oracle/scripts/setup
      - ./config:/opt/oracle/scripts/startup
      - ./backup:/opt/oracle/backup/scripts
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  oracle_data:
    driver: local
  oracle_backup:
    driver: local